# theme: universe
background              #000000
foreground              #EEEEEE
cursor                  #EEEEEE
cursor_text_color       #000000
selection_foreground    #EEEEEE
selection_background    #1a1a1a
active_tab_background   #0a0a0a
active_tab_foreground   #EEEEEE
inactive_tab_background #050505
inactive_tab_foreground #666666

background_opacity 0.90
