background = 0xFF000000
base = 0xFF0a0a0a
text = 0xFFEEEEEE
alternate_base = 0xFF0f0f0f
bright_text = 0xFFEEEEEE
accent = 0xFFEEEEEE
link_text = 0xFFEEEEEE
accent_secondary = 0xFF888888
font_family = "IBM Plex Mono"
font_family_monospace = "monospace"
font_size = 13
small_font_size = 10
rounding_large = 0
rounding_small = 0
